#!/bin/bash

# signal_complete takes a container name and a status and creates a file in the
# "status" directory whose contents are the provided status.  This can be
# leveraged by dependent containers via the `wait_for` command.

mkdir -p "/tmp/status"
echo "$2" > "/tmp/status/$1"
printf "Marked %s as %s.\n" "$1" "$2"
