# Site-level host catalogue.  This info feeds the Templater
# kustomize plugin config in the hostgenerator-m3 function.
apiVersion: airshipit.org/v1alpha1
kind: VariableCatalogue
metadata:
  name: host-catalogue
  labels:
    airshipit.org/deploy-k8s: "false"

hosts:
  m3:
    node01:
      bootMode: legacy
      macAddress: 52:54:00:b6:ed:31
      bmcAddress: redfish+http://10.23.25.1:8000/redfish/v1/Systems/air-target-1
      bmcUsername: root
      bmcPassword: r00tme
      disableCertificateVerification: false
      ipAddresses:
        oam-ipv4: 10.23.25.102
        pxe-ipv4: 10.23.24.102
      macAddresses:
        oam: 52:54:00:9b:27:4c
        pxe: 52:54:00:b6:ed:31
      hardwareProfile: default # defined in the hostgenerator-m3 function
      labels: # optional
        airshipit.org/example-label: "label-bmh-like-this"
    node02:
      bootMode: legacy
      macAddress: 52:54:00:b6:ed:02
      bmcAddress: redfish+https://10.23.25.1:8443/redfish/v1/Systems/air-ephemeral
      bmcUsername: username
      bmcPassword: password
      disableCertificateVerification: false
      ipAddresses:
        oam-ipv4: 10.23.25.101
        pxe-ipv4: 10.23.24.101
      macAddresses:
        oam: 52:54:00:9b:27:02
        pxe: 52:54:00:b6:ed:02
      hardwareProfile: default
    node03:
      bootMode: legacy
      macAddress: 52:54:00:b6:ed:23
      bmcAddress: redfish+http://10.23.25.1:8000/redfish/v1/Systems/air-worker-1
      bmcUsername: username
      bmcPassword: password
      disableCertificateVerification: false
      ipAddresses:
        oam-ipv4: 10.23.25.103
        pxe-ipv4: 10.23.24.103
      macAddresses:
        oam: 52:54:00:9b:27:07
        pxe: 52:54:00:b6:ed:23
      hardwareProfile: default # defined in the hardwareprofile-example function
    node04:
      bootMode: legacy
      macAddress: 52:54:00:01:71:d8
      bmcAddress: redfish+http://10.23.25.1:8000/redfish/v1/Systems/air-target-2
      bmcUsername: username
      bmcPassword: password
      disableCertificateVerification: false
      ipAddresses:
        oam-ipv4: 10.23.25.104
        pxe-ipv4: 10.23.24.104
      macAddresses:
        oam: 52:54:00:f0:57:e0
        pxe: 52:54:00:01:71:d8
      hardwareProfile: default # defined in the hostgenerator-m3 function
    node05:
      bootMode: legacy
      macAddress: 52:54:00:a3:ee:18
      bmcAddress: redfish+http://10.23.25.1:8000/redfish/v1/Systems/air-target-3
      bmcUsername: username
      bmcPassword: password
      disableCertificateVerification: false
      ipAddresses:
        oam-ipv4: 10.23.25.105
        pxe-ipv4: 10.23.24.105
      macAddresses:
        oam: 52:54:00:91:36:49
        pxe: 52:54:00:a3:ee:18
      hardwareProfile: default # defined in the hostgenerator-m3 function
    node06:
      bootMode: legacy
      macAddress: 52:54:00:b6:ed:19
      bmcAddress: redfish+http://10.23.25.1:8000/redfish/v1/Systems/air-worker-2
      bmcUsername: username
      bmcPassword: password
      disableCertificateVerification: false
      ipAddresses:
        oam-ipv4: 10.23.25.106
        pxe-ipv4: 10.23.24.106
      macAddresses:
        oam: 52:54:00:9b:27:08
        pxe: 52:54:00:b6:ed:19
      hardwareProfile: default # defined in the hardwareprofile-example function

