# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Ensure the VM console log directory exists
  file:
    path: "{{ console_log_path | dirname}}"
    state: directory
    recurse: true
    mode: 0770
  become: true
  when: "libvirt_domain.console_log_enabled | default(false)"

- name: Validate VM interfaces
  include_tasks: check-interface.yaml
  vars:
    interface: "{{ item }}"
  with_items: "{{ libvirt_domain.interfaces }}"

- name: Ensure the VM is defined
  virt:
    name: "{{ libvirt_domain.name }}"
    command: define
    xml: "{{ libvirt_domain.xml | default(libvirt_domain_template_default) }}"

- name: Ensure the VM is started at boot
  virt:
    name: "{{ libvirt_domain.name }}"
    autostart: "{{ libvirt_domain.autostart | default(false) }}"
    state: "{{ libvirt_domain.state | default('running') }}"
