// +build !ignore_autogenerated

/*
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplyConfig) DeepCopyInto(out *ApplyConfig) {
	*out = *in
	out.WaitOptions = in.WaitOptions
	out.PruneOptions = in.PruneOptions
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplyConfig.
func (in *ApplyConfig) DeepCopy() *ApplyConfig {
	if in == nil {
		return nil
	}
	out := new(ApplyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplyPruneOptions) DeepCopyInto(out *ApplyPruneOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplyPruneOptions.
func (in *ApplyPruneOptions) DeepCopy() *ApplyPruneOptions {
	if in == nil {
		return nil
	}
	out := new(ApplyPruneOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplyWaitOptions) DeepCopyInto(out *ApplyWaitOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplyWaitOptions.
func (in *ApplyWaitOptions) DeepCopy() *ApplyWaitOptions {
	if in == nil {
		return nil
	}
	out := new(ApplyWaitOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaremetalHostSelector) DeepCopyInto(out *BaremetalHostSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaremetalHostSelector.
func (in *BaremetalHostSelector) DeepCopy() *BaremetalHostSelector {
	if in == nil {
		return nil
	}
	out := new(BaremetalHostSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaremetalManager) DeepCopyInto(out *BaremetalManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaremetalManager.
func (in *BaremetalManager) DeepCopy() *BaremetalManager {
	if in == nil {
		return nil
	}
	out := new(BaremetalManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BaremetalManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaremetalManagerSpec) DeepCopyInto(out *BaremetalManagerSpec) {
	*out = *in
	out.HostSelector = in.HostSelector
	out.OperationOptions = in.OperationOptions
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaremetalManagerSpec.
func (in *BaremetalManagerSpec) DeepCopy() *BaremetalManagerSpec {
	if in == nil {
		return nil
	}
	out := new(BaremetalManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaremetalOperationOptions) DeepCopyInto(out *BaremetalOperationOptions) {
	*out = *in
	out.RemoteDirect = in.RemoteDirect
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaremetalOperationOptions.
func (in *BaremetalOperationOptions) DeepCopy() *BaremetalOperationOptions {
	if in == nil {
		return nil
	}
	out := new(BaremetalOperationOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootConfiguration) DeepCopyInto(out *BootConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.BootstrapContainer = in.BootstrapContainer
	out.EphemeralCluster = in.EphemeralCluster
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootConfiguration.
func (in *BootConfiguration) DeepCopy() *BootConfiguration {
	if in == nil {
		return nil
	}
	out := new(BootConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BootConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapContainer) DeepCopyInto(out *BootstrapContainer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapContainer.
func (in *BootstrapContainer) DeepCopy() *BootstrapContainer {
	if in == nil {
		return nil
	}
	out := new(BootstrapContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cluster) DeepCopyInto(out *Cluster) {
	*out = *in
	out.ClusterAPIRef = in.ClusterAPIRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster.
func (in *Cluster) DeepCopy() *Cluster {
	if in == nil {
		return nil
	}
	out := new(Cluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAPIRef) DeepCopyInto(out *ClusterAPIRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAPIRef.
func (in *ClusterAPIRef) DeepCopy() *ClusterAPIRef {
	if in == nil {
		return nil
	}
	out := new(ClusterAPIRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMap) DeepCopyInto(out *ClusterMap) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Map != nil {
		in, out := &in.Map, &out.Map
		*out = make(map[string]*Cluster, len(*in))
		for key, val := range *in {
			var outVal *Cluster
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(Cluster)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMap.
func (in *ClusterMap) DeepCopy() *ClusterMap {
	if in == nil {
		return nil
	}
	out := new(ClusterMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterMap) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Clusterctl) DeepCopyInto(out *Clusterctl) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]*Provider, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Provider)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.InitOptions != nil {
		in, out := &in.InitOptions, &out.InitOptions
		*out = new(InitOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.MoveOptions != nil {
		in, out := &in.MoveOptions, &out.MoveOptions
		*out = new(MoveOptions)
		**out = **in
	}
	if in.AdditionalComponentVariables != nil {
		in, out := &in.AdditionalComponentVariables, &out.AdditionalComponentVariables
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ImageMetas != nil {
		in, out := &in.ImageMetas, &out.ImageMetas
		*out = make(map[string]ImageMeta, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Clusterctl.
func (in *Clusterctl) DeepCopy() *Clusterctl {
	if in == nil {
		return nil
	}
	out := new(Clusterctl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Clusterctl) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EphemeralCluster) DeepCopyInto(out *EphemeralCluster) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EphemeralCluster.
func (in *EphemeralCluster) DeepCopy() *EphemeralCluster {
	if in == nil {
		return nil
	}
	out := new(EphemeralCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericContainer.
func (in *GenericContainer) DeepCopy() *GenericContainer {
	if in == nil {
		return nil
	}
	out := new(GenericContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenericContainer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageMeta) DeepCopyInto(out *ImageMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageMeta.
func (in *ImageMeta) DeepCopy() *ImageMeta {
	if in == nil {
		return nil
	}
	out := new(ImageMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitOptions) DeepCopyInto(out *InitOptions) {
	*out = *in
	if in.BootstrapProviders != nil {
		in, out := &in.BootstrapProviders, &out.BootstrapProviders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InfrastructureProviders != nil {
		in, out := &in.InfrastructureProviders, &out.InfrastructureProviders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ControlPlaneProviders != nil {
		in, out := &in.ControlPlaneProviders, &out.ControlPlaneProviders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KubeConfigRef != nil {
		in, out := &in.KubeConfigRef, &out.KubeConfigRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitOptions.
func (in *InitOptions) DeepCopy() *InitOptions {
	if in == nil {
		return nil
	}
	out := new(InitOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IsoConfiguration) DeepCopyInto(out *IsoConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.IsoContainer != nil {
		in, out := &in.IsoContainer, &out.IsoContainer
		*out = new(IsoContainer)
		**out = **in
	}
	if in.Isogen != nil {
		in, out := &in.Isogen, &out.Isogen
		*out = new(Isogen)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IsoConfiguration.
func (in *IsoConfiguration) DeepCopy() *IsoConfiguration {
	if in == nil {
		return nil
	}
	out := new(IsoConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IsoConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IsoContainer) DeepCopyInto(out *IsoContainer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IsoContainer.
func (in *IsoContainer) DeepCopy() *IsoContainer {
	if in == nil {
		return nil
	}
	out := new(IsoContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Isogen) DeepCopyInto(out *Isogen) {
	*out = *in
	out.UserDataSelector = in.UserDataSelector
	out.NetworkConfigSelector = in.NetworkConfigSelector
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Isogen.
func (in *Isogen) DeepCopy() *Isogen {
	if in == nil {
		return nil
	}
	out := new(Isogen)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeConfig) DeepCopyInto(out *KubeConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeConfig.
func (in *KubeConfig) DeepCopy() *KubeConfig {
	if in == nil {
		return nil
	}
	out := new(KubeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesApply) DeepCopyInto(out *KubernetesApply) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Config = in.Config
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesApply.
func (in *KubernetesApply) DeepCopy() *KubernetesApply {
	if in == nil {
		return nil
	}
	out := new(KubernetesApply)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubernetesApply) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoveOptions) DeepCopyInto(out *MoveOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoveOptions.
func (in *MoveOptions) DeepCopy() *MoveOptions {
	if in == nil {
		return nil
	}
	out := new(MoveOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Phase) DeepCopyInto(out *Phase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Phase.
func (in *Phase) DeepCopy() *Phase {
	if in == nil {
		return nil
	}
	out := new(Phase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Phase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhaseConfig) DeepCopyInto(out *PhaseConfig) {
	*out = *in
	if in.ExecutorRef != nil {
		in, out := &in.ExecutorRef, &out.ExecutorRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhaseConfig.
func (in *PhaseConfig) DeepCopy() *PhaseConfig {
	if in == nil {
		return nil
	}
	out := new(PhaseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhasePlan) DeepCopyInto(out *PhasePlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Phases != nil {
		in, out := &in.Phases, &out.Phases
		*out = make([]PhaseStep, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhasePlan.
func (in *PhasePlan) DeepCopy() *PhasePlan {
	if in == nil {
		return nil
	}
	out := new(PhasePlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PhasePlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhaseStep) DeepCopyInto(out *PhaseStep) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhaseStep.
func (in *PhaseStep) DeepCopy() *PhaseStep {
	if in == nil {
		return nil
	}
	out := new(PhaseStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Provider) DeepCopyInto(out *Provider) {
	*out = *in
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Provider.
func (in *Provider) DeepCopy() *Provider {
	if in == nil {
		return nil
	}
	out := new(Provider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteDirectOptions) DeepCopyInto(out *RemoteDirectOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteDirectOptions.
func (in *RemoteDirectOptions) DeepCopy() *RemoteDirectOptions {
	if in == nil {
		return nil
	}
	out := new(RemoteDirectOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplacementTransformer.
func (in *ReplacementTransformer) DeepCopy() *ReplacementTransformer {
	if in == nil {
		return nil
	}
	out := new(ReplacementTransformer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReplacementTransformer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Templater.
func (in *Templater) DeepCopy() *Templater {
	if in == nil {
		return nil
	}
	out := new(Templater)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Templater) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
