apiVersion: airshipit.org/v1alpha1
kind: ReplacementTransformer
metadata:
  name: baremetal-operator-versions-replacements
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: localhost/replacement-transformer
replacements:
# Container versions for the ironic Deployment
- source:
    objref:
      kind: VersionsCatalogue
      name: versions-airshipctl
    fieldref: "{.spec.images.baremetal_operator.metal3_baremetal_operator.baremetal_operator.image}"
  target:
    objref:
      kind: Deployment
      name: baremetal-operator-controller-manager
    fieldrefs: ["{.spec.template.spec.containers[?(.name == 'manager')].image}"]
- source:
    objref:
      kind: VersionsCatalogue
      name: versions-airshipctl
    fieldref: "{.spec.images.baremetal_operator.metal3_baremetal_operator.kube_rbac_proxy.image}"
  target:
    objref:
      kind: Deployment
      name: baremetal-operator-controller-manager
    fieldrefs: ["{.spec.template.spec.containers[?(.name == 'kube-rbac-proxy')].image}"]
